package com.example.rodas.activity;

import android.content.Context;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.Adapter;
import android.widget.ArrayAdapter;
import android.widget.Spinner;
import android.widget.Toast;

import com.example.rodas.R;
import com.example.rodas.model.Carro;
import com.example.rodas.model.Movimentacao;

public class InformacoesCarroActivity extends AppCompatActivity {
    private Spinner Marca,Modelo,AnoFab = null;
    private Carro carro;
    private String modeloCar;
    private String marcaCar;
    private String anoFab;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_informacoes_carro);
        inicializa();
        CarregarDadosSpinnerMarca();
        CarregardadosSpinnerModelo();
        CarregardadosSpinnerAnos();
    }

    private void CarregardadosSpinnerAnos() {
        String[] ArrayAno = new String[]{
                "ANO DE FABRICAÇÃO",
                "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019"
        };
        ArrayAdapter<String> adapter = new ArrayAdapter<String>(this,
                android.R.layout.simple_spinner_item, ArrayAno);
        adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
        AnoFab.setAdapter(adapter);
    }

    private void CarregardadosSpinnerModelo() {
        String[] ArrayModelo = new String[]{
                "MODELO",
                "A-10",
                "A-20",
                "AGILE",
                "ASTRA",
                "BLAZER",
                "BONANZA",
                "C-10",
                "C-20",
                "CALIBRA",
                "CAMARO",
                "CAPRICE",
                "CAPTIVA",
                "CARAVAN",
                "CAVALIER",
                "CELTA",
                "CHEVY",
                "CHEYNNE",
                "COBALT",
                "CORSA",
                "CORVETTE",
                "CRUZE",
                "D-10",
                "D-20",
                "IPANEMA",
                "KADETT",
                "LUMINA",
                "MALIBU",
                "MERIVA",
                "MONTANA",
                "OMEGA",
                "OPALA",
                "PRISMA",
                "S10",
                "SILVERADO",
                "SONIC",
                "SONOMA",
                "SPACEVAN",
                "SS10",
                "SUBURBAN",
                "SYCLONE",
                "TIGRA",
                "TRACKER",
                "TRAFIC",
                "VECTRA",
                "VERANEIO",
                "ZAFIRA",
                "BEL AIR",
                "C-14",
                "C-15",
                "BRASIL",
                "ONIX",
                "SPIN",
                "TRAILBLAZER",
                "CLUB COUPE",
                "GMC 100",
                "STYLELINE",
                "YUKON",
                "SSR",
                "IMPALA",
                "GRAND BLAZER",
                "ASTRO",
                "MONZA",
                "CHEVETTE",
                "TRAX",
                "CORISCO",
                "CHEVELLE",
                "VENTURE",
                "FLEETLINE",
                "FLEETMASTER",
                "DELUXE",
                "MASTER",
                "CLASSIC",
                "MARAJO",
                "SUPREMA",
                "AMAROK",
                "APOLLO",
                "BORA",
                "CARAVELLE",
                "CORRADO",
                "EOS",
                "EUROVAN",
                "FOX",
                "FUSCA",
                "GOL",
                "GOLF",
                "JETTA",
                "KOMBI",
                "LOGUS",
                "PARATI",
                "PASSAT",
                "POINTER",
                "POLO",
                "SANTANA",
                "SAVEIRO",
                "SPACEFOX",
                "TIGUAN",
                "TOUAREG",
                "VOYAGE",
                "BRASILIA",
                "TL",
                "VARIANT",
                "SP2",
                "POLAUTO",
                "CC",
                "TOURAN",
                "TRANSPORTER",
                "UP",
                "NEW BEETLE",
                "QUANTUM",
                "CROSSFOX",
                "GOLF VARIANT",
                "SPACE CROSS",
                "147",
                "500",
                "BRAVA",
                "BRAVO",
                "COUPE",
                "DOBLO",
                "DUCATO CARGO",
                "DUNA",
                "ELBA",
                "FIORINO",
                "FREEMONT",
                "GRAND SIENA",
                "IDEA",
                "LINEA",
                "MAREA",
                "OGGI",
                "PALIO",
                "PANORAMA",
                "PREMIO",
                "PUNTO",
                "SIENA",
                "STILO",
                "STRADA",
                "TEMPRA",
                "TIPO",
                "UNO",
                "140",
                "PALIO WEEKEND",
                "600",
                "TOPOLINO",
                "BALILLA",
                "MILLE",
                "MOBI",
                "TORO",
                "CLASSE A",
                "CLASSE B",
                "CLASSE R",
                "CLASSE GLK",
                "SPRINTER",
                "CLASSE CLC",
                "CLASSE CLS",
                "CLASSE SLK",
                "CLASSE C",
                "CLASSE E",
                "CLASSE CL",
                "CLASSE CLK",
                "CLASSE S",
                "CLASSE SL",
                "CLASSE SLS",
                "CLASSE G",
                "CLASSE GL",
                "CLASSE M",
                "170",
                "300D",
                "CLASSE TE",
                "190",
                "CLASSE CLA",
                "CLASSE V",
                "VANEO",
                "CITAN",
                "VARIO",
                "CLASSE S CLASSICO",
                "AIRCROSS",
                "AX",
                "BERLINGO",
                "BX",
                "C3",
                "C4",
                "C5",
                "C6",
                "C8",
                "DS3",
                "EVASION",
                "JUMPER",
                "XANTIA",
                "XM",
                "XSARA",
                "ZX",
                "C4 PALLAS",
                "C4 PICASSO",
                "C4 VTR",
                "XSARA PICASSO",
                "C3 PICASSO",
                "GRAND C4 PICASSO",
                "JUMPER MINIBUS",
                "JUMPER VETRATO",
                "ONCE",
                "C4 LOUNGE",
                "C3 SOLARIS",
                "C3 XTR",
                "C4 SOLARIS",
                "C5 BREAK/TOURER",
                "XSARA BREAK",
                "XSARA VTS",
                "XANTIA BREAK",
                "XM BREAK",
                "C15",
                "NEMO",
                "VISA",
                "C1",
                "C2",
                "C3 PLURIEL",
                "DS4",
                "DS5",
                "JUMPY",
                "C-CROSSER",
                "C35",
                "C25",
                "CX",
                "CX BREAK",
                "AXEL",
                "DYANE",
                "GS/GSA",
                "GS/GSA BREAK",
                "MEHARI",
                "SAXO",
                "SM",
                "ELYSEE",
                "MINI STAR FAMILY",
                "MINI STAR UTILITY",
                "STAR TRUCK",
                "STAR",
                "STAR VAN CARGO",
                "STAR VAN PASSAGEIROS",
                "ACCORD",
                "CITY",
                "CIVIC",
                "CR-V",
                "FIT",
                "ODYSSEY",
                "PASSPORT",
                "PRELUDE",
                "ACTY",
                "AIRWAVE",
                "ASCOT",
                "BALLADE",
                "BEAT",
                "CR-X",
                "CONCERTO",
                "CR-Z",
                "DOMANI",
                "EDIX",
                "ELEMENT",
                "EV PLUS",
                "FCX",
                "FR-V",
                "HR-V",
                "HSC",
                "INSIGHT",
                "LIFE DUNK",
                "LOGO",
                "MOBILIO",
                "ORTHIA",
                "PARTNER VAN",
                "PILOT",
                "RIDGELINE",
                "S2000",
                "S600",
                "S500",
                "S800",
                "STEPWGN",
                "STREAM",
                "THATS",
                "VAMOZ",
                "Z",
                "ZEST",
                "FIT TWIST",
                "FORESTER",
                "IMPREZA",
                "LEGACY",
                "OUTBACK",
                "SVX",
                "TRIBECA",
                "VIVIO",
                "NEW XV",
                "IMPREZA WRX HATCH",
                "IMPREZA WRX STI HATCH",
                "IMPREZA WRX STI SEDAN",
                "IMPREZA WRX SEDAN",
                "348",
                "355",
                "360",
                "456",
                "550",
                "575M",
                "612",
                "CALIFORNIA",
                "F430",
                "F599",
                "F12",
                "458 SPIDER",
                "458 ITALIA",
                "FF",
                "599",
                "SA",
                "CHALLENGE",
                "SUPERAMERICA",
                "F430 SPIDER",
                "430",
                "612 SESSANTA",
                "599 GTB",
                "SCUDERIA SPIDER",
                "512",
                "456 GT",
                "348 GTS",
                "348 SPIDER",
                "F355",
                "F355 SPIDER",
                "F50",
                "355 SPIDER",
                "360 MODENA",
                "ENZO",
                "380 GTB",
                "VEYRON",
                "GALLARDO",
                "MURCIELAGO",
                "350 GT",
                "400 GT",
                "MIURA",
                "ISLERO",
                "ESPADA",
                "COUNTACH",
                "DIABLO",
                "ZAGATO",
                "ALAR",
                "LM002",
                "REVENTON",
                "ANKONIAN",
                "AVENTADOR",
                "SESTO ELEMENTO",
                "HURACAN",
                "AEROSTAR",
                "ASPIRE",
                "BELINA",
                "CLUB WAGON",
                "CONTOUR",
                "CORCEL II",
                "COURIER",
                "CROWN VICTORIA",
                "DEL REY",
                "ECOSPORT",
                "EDGE",
                "ESCORT",
                "EXPEDITION",
                "EXPLORER",
                "F-100",
                "F-1000",
                "F-150",
                "F-250",
                "FIESTA",
                "FOCUS",
                "FURGLAINE",
                "FUSION",
                "IBIZA",
                "KA",
                "MONDEO",
                "MUSTANG",
                "PAMPA",
                "PROBE",
                "RANGER",
                "VERSAILLES ROYALE",
                "TAURUS",
                "THUNDERBIRD",
                "TRANSIT",
                "VERONA",
                "VERSAILLES",
                "WINDSTAR",
                "BRASILVAN",
                "CORCEL",
                "FOCUS SEDAN",
                "FIESTA SEDAN",
                "FIESTA TRAIL",
                "ESCORT SW",
                "F-01",
                "FALCON",
                "GALAXIE",
                "MAVERICK",
                "MODELO A",
                "NEW FIESTA",
                "NEW FIESTA SEDAN",
                "TRANSIT PASSAGEIRO",
                "TRANSIT CHASSI",
                "SIERRA",
                "F-85",
                "ANGLIA",
                "TT",
                "DE LUXE",
                "CUSTOM",
                "T-BUCKET",
                "KA SPORT",
                "FREESTYLE",
                "RANGER CD",
                "MONDEO SW",
                "ESCORT SEDAN",
                "ESCORT CONVERSIVEL",
                "EXCURSION",
                "F-10000",
                "PHAETON",
                "TORINO",
                "ESCORT XR3",
                "KA SEDAN",
                "FOCUS FASTBACK",
                "ACCENT",
                "ATOS",
                "AZERA",
                "COUPE",
                "ELANTRA",
                "EXCEL",
                "GALLOPER",
                "GENESIS",
                "H1",
                "H100",
                "I30",
                "IX35",
                "MATRIX",
                "PORTER",
                "SANTA FE",
                "SCOUPE",
                "SONATA",
                "TERRACAN",
                "TRAJET",
                "TUCSON",
                "VELOSTER",
                "VERACRUZ",
                "PRIME",
                "TIBURON",
                "HB20",
                "EQUUS",
                "HB20X",
                "HB20S",
                "HB20R",
                "GRAND SANTA FE",
                "J3",
                "J5",
                "J6",
                "J3 TURIN",
                "J2",
                "J3S",
                "T140",
                "T8",
                "T6",
                "T5",
                "AM-825",
                "HI-TOPIC",
                "ROCSTA",
                "TOPIC",
                "TOWNER",
                "BESTA",
                "BONGO",
                "CADENZA",
                "CARENS",
                "CARNIVAL",
                "CERATO",
                "CERES",
                "CLARUS",
                "MAGENTIS",
                "MOHAVE",
                "OPIRUS",
                "OPTIMA",
                "PICANTO",
                "SEPHIA",
                "SHUMA",
                "SORENTO",
                "SOUL",
                "SPORTAGE",
                "CERATO KOUP",
                "GRAND BESTA",
                "QUORIS",
                "GRAND CARNIVAL",
                "BR-800",
                "CARAJAS",
                "TOCANTINS",
                "XAVANTE",
                "VIP",
                "X12",
                "SUPERMINI",
                "X15",
                "G15",
                "X20",
                "ITAIPU",
                "G800",
                "XEF",
                "MOTOMACHINE",
                "BUGATO",
                "QT",
                "AVENGER",
                "DAKOTA",
                "JOURNEY",
                "RAM",
                "STEALTH",
                "POLARA",
                "NITRO",
                "CHALLENGER",
                "DART",
                "LE BARON",
                "CORDOBA",
                "CHARGER",
                "D100",
                "CUSTOM ROYAL",
                "MAGNUM",
                "KINGSWAY",
                "300C",
                "CARAVAN",
                "CIRRUS",
                "GRAN CARAVAN",
                "LE BARON",
                "NEON",
                "PT CRUISER",
                "SEBRING",
                "STRATUS",
                "TOWN E COUNTRY",
                "VISION",
                "WINDSOR",
                "CROSSFIRE",
                "CORDOBA",
                "300M",
                "300C TOURING",
                "ACTYON SPORTS",
                "CHAIRMAN",
                "ISTANA",
                "KORANDO",
                "KYRON",
                "MUSSO",
                "REXTON",
                "NEW ACTYON SPORTS",
                "ACTYON",
                "106",
                "205",
                "206",
                "207",
                "3008",
                "306",
                "307",
                "308",
                "405",
                "406",
                "407",
                "408",
                "504",
                "505",
                "508",
                "605",
                "607",
                "806",
                "807",
                "BOXER",
                "HOGGAR",
                "PARTNER",
                "RCZ",
                "207 SW",
                "307 SEDAN",
                "307 SW",
                "207 SEDAN",
                "207 QUIKSILVER",
                "207 ESCAPADE",
                "308 CC",
                "BOXER PASSAGEIRO",
                "306 CABRIOLET",
                "407 SW",
                "307 CC",
                "306 SW",
                "208",
                "HOGGAR ESCAPADE",
                "2008",
                "AVALON",
                "BANDEIRANTE",
                "CAMRY",
                "CELICA",
                "COROLLA",
                "CORONA",
                "HILUX",
                "LAND CRUISER",
                "MR-2",
                "PASEO",
                "PREVIA",
                "RAV4",
                "SUPRA",
                "COROLLA FIELDER",
                "HILUX SW4",
                "SR5",
                "VITZ",
                "ETIOS",
                "PRIUS",
                "T-100",
                "COROLLA XRS",
                "ETIOS SEDAN",
                "ETIOS CROSS",
                "21 SEDAN",
                "CLIO",
                "DUSTER",
                "EXPRESS",
                "FLUENCE",
                "KANGOO",
                "LAGUNA",
                "LOGAN",
                "MASTER",
                "MEGANE",
                "SAFRANE",
                "SANDERO",
                "SCENIC",
                "SYMBOL",
                "TRAFIC",
                "TWINGO",
                "CLIO SEDAN",
                "MEGANE GRAND TOUR",
                "SANDERO STEPWAY",
                "7TL",
                "19",
                "GORDINI",
                "SANDERO GT",
                "MEGANE SEDAN",
                "21 NEVADA",
                "MASTER MINIBUS",
                "DUSTER OROCH",
                "SANDERO RS",
                "INTEGRA",
                "LEGEND",
                "NSX",
                "ZDX",
                "TL",
                "MDX",
                "GT2",
                "GT",
                "GTL",
                "GTM",
                "C2",
                "CRX",
                "AC 2000",
                "MARRUA",
                "145",
                "147",
                "155",
                "156",
                "164",
                "166",
                "2300",
                "SPIDER",
                "TI 80",
                "DB9 COUPE",
                "DB9 VOLANTE",
                "VIRAGE COUPE",
                "RAPIDE S",
                "V12 VANTAGE",
                "V8 VANTAGE COUPE",
                "V8 VANTAGE ROADSTER",
                "V8 VANTAGE S COUPE",
                "V8 VANTAGE S ROADSTER",
                "VANQUISH COUPE",
                "VANQUISH VOLANTE",
                "V12 ZAGATO",
                "DB5",
                "DBS",
                "DBS VOLANTE",
                "CYGNET",
                "ONE-77",
                "DBR9",
                "100",
                "80",
                "A1",
                "A3",
                "A4 SEDAN",
                "A5 COUPE",
                "A6 SEDAN",
                "A7",
                "A8",
                "Q3",
                "Q5",
                "Q7",
                "R8",
                "RS3",
                "RS4",
                "RS5",
                "RS6",
                "S3",
                "S4 SEDAN",
                "S6 SEDAN",
                "S8",
                "TT",
                "TTS",
                "A4 AVANT",
                "S4 AVANT",
                "A5 SPORTBACK",
                "A5 CABRIOLET",
                "S5 COUPE",
                "S5 SPORTBACK",
                "S5 CABRIOLET",
                "A6 AVANT",
                "A6 ALLROAD",
                "S6 AVANT",
                "S7",
                "TT ROADSTER",
                "TT RS",
                "TT RS ROADSTER",
                "TTS ROADSTER",
                "R8 SPYDER",
                "R8 GT",
                "R8 GT SPYDER",
                "A4 CABRIOLET",
                "A1 SPORTBACK",
                "A1 QUATTRO",
                "A3 SPORTBACK",
                "RS4 AVANT",
                "A8L W12",
                "R8 V10",
                "RX",
                "330",
                "520",
                "730",
                "M1",
                "SERIE Z",
                "120 CABRIO",
                "320 TOURING",
                "330 CABRIO",
                "SERIE 5 TOURING",
                "SERIE 6 CABRIO",
                "SERIE M CONVERSIVEL",
                "M5 TOURING",
                "SERIE Z ROADSTER",
                "118",
                "120",
                "130",
                "BAVARIA",
                "C-2800",
                "318",
                "320",
                "318 CABRIO",
                "325 CABRIO",
                "530",
                "540",
                "550",
                "740",
                "750",
                "760",
                "X1",
                "X3",
                "X5",
                "X6",
                "840",
                "850",
                "645",
                "650",
                "M3",
                "M5",
                "M6",
                "X6 M",
                "RIVIERA",
                "COUPE",
                "CENTURY",
                "APOLLO",
                "CENTURION",
                "EIGHT",
                "ELECTRA",
                "ESTATE WAGON",
                "GRAN SPORT",
                "GSX",
                "INVICTA",
                "LESABRE",
                "LIMITED",
                "PARK AVENUE",
                "RAINIER",
                "REATTA",
                "REGAL",
                "RENDEZVOUS",
                "ROADMASTER",
                "ROYAUM",
                "SKYHAWK",
                "SKYLARK",
                "SOMERSET",
                "SPECIAL",
                "SPORT WAGON",
                "SUPER",
                "TERRAZA",
                "WILDCAT",
                "LACROSSE",
                "ENCLAVE",
                "GL8",
                "HRV",
                "LUCERNE",
                "JAVALI",
                "350Z",
                "ALTIMA",
                "AX",
                "D-21",
                "FRONTIER",
                "KING-CAB",
                "LIVINA",
                "MARCH",
                "MAXIMA",
                "MURANO",
                "NX",
                "PATHFINDER",
                "PRIMERA",
                "QUEST",
                "SENTRA",
                "STANZA",
                "180SX",
                "TERRANO",
                "TIIDA",
                "VERSA",
                "X-TRAIL",
                "XTERRA",
                "ZX",
                "370Z",
                "LIVINA X-GEAR",
                "GRAND LIVINA",
                "200SX",
                "240SX",
                "CIELO",
                "FACE",
                "QQ",
                "S-18",
                "TIGGO",
                "CELER",
                "CELER SEDAN",
                "CIELO SEDAN",
                "CL-244",
                "CL-330",
                "ESPERO",
                "LANOS",
                "LEGANZA",
                "NUBIRA",
                "PRINCE",
                "RACER",
                "SUPER SALON",
                "TICO",
                "BROUGHAM",
                "CHAIRMAN",
                "DAMAS",
                "GENTRA",
                "MAEPSY",
                "ISTANA",
                "KALOS",
                "KORANDO",
                "LACETTI",
                "LEMANS",
                "MATIZ",
                "MUSSO",
                "NEXIA",
                "REZZO",
                "ROYALE PRINCE",
                "ROYALE SALON",
                "STATESMAN",
                "TOSCA",
                "WINSTORM",
                "APPLAUSE",
                "CHARADE",
                "CUORE",
                "FEROZA",
                "GRAN MOVE",
                "MOVE VAN",
                "TERIOS",
                "400 SERIES",
                "850",
                "900 SERIES",
                "100 SERIES",
                "200 SERIES",
                "300 SERIES",
                "66",
                "700 SERIES",
                "AMAZON",
                "C303",
                "DUETT",
                "L3314",
                "OV 4",
                "P1800",
                "SUGGA",
                "C70",
                "C30",
                "544",
                "S40",
                "S60",
                "S70",
                "S80",
                "V40",
                "V50",
                "V60",
                "V70",
                "S90",
                "XC60",
                "XC70",
                "XC90",
                "P1900",
                "PV36",
                "PV444",
                "PV544",
                "PV51",
                "PV654",
                "C50",
                "SPORTSMAN",
                "CANDANGO",
                "BELCAR",
                "CAICARA",
                "CARCARA",
                "FISSORE",
                "MALZONI",
                "VEMAGUET",
                "BALENO",
                "GRAND VITARA",
                "IGNIS",
                "JIMNY",
                "SUPER CARRY",
                "SWIFT",
                "SX4",
                "VITARA",
                "WAGON R",
                "AERIO",
                "ALTO",
                "APV",
                "KEI",
                "LAPIN",
                "MR WAGON",
                "XL-7",
                "VERONA",
                "M-100",
                "PLUTUS",
                "START",
                "ULC",
                "ENGESA",
                "CAMPER",
                "MASTER",
                "SUPER 90 COUPE",
                "TRANS-AM",
                "TRANS-SPORT",
                "SOLSTICE",
                "911",
                "BOXSTER",
                "CAYENNE",
                "CAYMAN",
                "PANAMERA",
                "SPEEDSTER 356",
                "SPYDER 550",
                "HOVER",
                "TOWNER",
                "H3",
                "LINHA FX",
                "LINHA G",
                "LINHA G COUPE",
                "LINHA G CONVERSIVEL",
                "LINHA M",
                "LINHA EX",
                "LINHA JX",
                "LINHA QX",
                "AMIGO",
                "HOMBRE",
                "RODEO",
                "DAIMLER",
                "S-TYPE",
                "X-TYPE",
                "MODELOS XJ",
                "MODELOS XK",
                "MARK V",
                "MODELOS XF",
                "F-TYPE",
                "MARK VII",
                "MARK VIII",
                "MARK IX",
                "MARK X",
                "E-TYPE",
                "C-TYPE",
                "D-TYPE",
                "MARK I",
                "MARK II",
                "CHEROKEE",
                "COMMANDER",
                "COMPASS",
                "GRAND CHEROKEE",
                "WRANGLER",
                "JEEP",
                "CJ5",
                "CJ3",
                "RENEGADE",
                "TOPIC VAN",
                "TOPIC FURGAO",
                "TOPIC ESCOLAR",
                "JIPE MONTEZ",
                "PICAPE MONTEZ",
                "M715",
                "LAIKA",
                "NIVA",
                "SAMARA",
                "DEFENDER",
                "DISCOVERY",
                "FREELANDER",
                "NEW RANGE",
                "RANGE ROVER",
                "ES",
                "GS",
                "IS-300",
                "LS",
                "RX",
                "SC",
                "320",
                "620",
                "X60",
                "530",
                "AVIATOR",
                "BLACKWOOD",
                "CAPRI",
                "CONTINENTAL",
                "LS",
                "MARK",
                "MARK LT",
                "MKR",
                "MKS",
                "MKX",
                "MKZ",
                "NAVIGATOR",
                "PREMIERE",
                "TOWN CAR",
                "VERSAILLES",
                "ZEPHYR",
                "H1",
                "ELAN",
                "ESPRIT",
                "SCORPIO",
                "XUV 500",
                "XYLO",
                "BOLERO",
                "THAR",
                "AXE",
                "LEGEND",
                "ARMADA",
                "CHASSI",
                "SCORPIO PICK-UP",
                "222",
                "228",
                "3200",
                "430",
                "COUPE",
                "GHIBLI",
                "GRANCABRIO",
                "GRANSPORT",
                "GRANTURISMO",
                "QUATTROPORTE",
                "SHAMAL",
                "SPIDER",
                "PICK-UP",
                "323",
                "626",
                "929",
                "B-2500",
                "B2200",
                "MILLENIA",
                "MPV",
                "MX-3",
                "MX-5",
                "NAVAJO",
                "PROTEGE",
                "RX",
                "CX-7",
                "MX-6",
                "MYSTIQUE",
                "SABLE",
                "MONTEREY",
                "COUGAR",
                "3000",
                "AIRTREK",
                "ASX",
                "COLT",
                "DIAMANT",
                "ECLIPSE",
                "EXPO",
                "GALANT",
                "GRANDIS",
                "L200",
                "L300",
                "LANCER",
                "MIRAGE",
                "MONTERO",
                "OUTLANDER",
                "PAJERO",
                "SPACE WAGON",
                "PAJERO FULL",
                "PAJERO DAKAR",
                "PAJERO TR4",
                "LANCER SPORTBACK",
                "LANCER EVOLUTION",
                "L200 TRITON SAVANA",
                "L200 TRITON",
                "PAJERO FULL 3D",
                "PAJERO SPORT",
                "550",
                "MG6",
                "COOPER",
                "ONE",
                "CABRIO",
                "COUPE",
                "ROADSTER",
                "COUNTRYMAN",
                "PACEMAN",
                "JOHN COOPER WORKS",
                "BG-TRUCK",
                "TOPSPORT",
                "TARGA",
                "X8",
                "SPORT",
                "MTS",
                "SPIDER",
                "KABRIO",
                "SAGA",
                "SAGA II",
                "787",
                "X11",
                "AUSTIN",
                "TORONADO",
                "SIX",
                "EIGHT",
                "DELUXE",
                "SERIES 60",
                "SERIES 70",
                "SERIES 80",
                "SERIES 90",
                "STARFIRE",
                "442",
                "CUTLASS",
                "CUTLASS SUPREME",
                "CUTLASS SALON",
                "CUTLASS CALAIS",
                "CUTLASS CIERA",
                "CUSTOM CRUISER",
                "VISTA CRUISER",
                "F-85",
                "FIRENZA",
                "ACHIEVA",
                "ALERO",
                "AURORA",
                "BRAVADA",
                "INTRIGUE",
                "SILHOUETTE",
                "ZONDA",
                "GRAN VOYAGER",
                "SUNDANCE",
                "SUPERBIRD",
                "FURY",
                "SPECIAL",
                "PROWLER",
                "TRAIL DUSTER",
                "VOYAGER",
                "SCAMP",
                "ARROW",
                "PT50",
                "PT57",
                "PT81",
                "PT105",
                "PT125",
                "EXPRESS",
                "VOYAGER EXPRESSO",
                "NEON",
                "LASER",
                "CARAVELLE",
                "STATION WAGON",
                "MODEL Q",
                "MODEL P6",
                "GTS",
                "GTB",
                "GTC",
                "GTE",
                "GT",
                "GT4R",
                "SPYDER",
                "GTI",
                "AM1",
                "AM2",
                "AM3",
                "AM4",
                "AMV",
                "CORDOBA",
                "IBIZA",
                "INCA",
                "COLHEITADEIRA",
                "A7",
                "A9",
                "A9 CARGO",
                "T20",
                "T20 BAU",
                "T22",
                "9000",
                "ALVORADA",
                "CHAMBORD",
                "PROFISSIONAL",
                "VEDETTE",
                "ARONDE",
                "1200S",
                "1000",
                "FORTWO",
                "FORTWO CABRIO",
                "CHAMPION",
                "STARK",
                "TR",
                "LUCENA",
                "SEVETSE",
                "RAGGE",
                "PANTANAL",
                "T-4",
                "T-5",
                "DEVILLE",
                "ELDORADO",
                "SEVILLE",
                "SRX4",
                "ESCALADE",
                "HUMMER",
                "BUGGY",
                "PICKUP F75",
                "RURAL",
                "ITAMARATY",
                "INTERLAGOS",
                "JEEP CJ",
                "SL-2",
                "CONVERSÍVEL",
                "EXPLORER",
                "TC",
                "RECORB",
                "MINX",
                "1500",
                "GAIOLA",
                "MATRIX 4X4",
                "PICK-UP",
                "VAN",
                "MP4",
                "F1",
                "GC2",
                "EC7",


        };
        ArrayAdapter<String> adapter = new ArrayAdapter<String>(this,
                android.R.layout.simple_spinner_item, ArrayModelo);
        adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
        Modelo.setAdapter(adapter);
    }

    private void CarregarDadosSpinnerMarca() {
        String[] ArrayMarca = new String[]{
                "MARCA",
                "CHEVROLET",
                "VOLKSWAGEN",
                "FIAT",
                "MERCEDES-BENZ",
                "CITROEN",
                "CHANA",
                "HONDA",
                "SUBARU",
                "FERRARI",
                "BUGATTI",
                "LAMBORGHINI",
                "FORD",
                "HYUNDAI",
                "JAC",
                "KIA",
                "GURGEL",
                "DODGE",
                "CHRYSLER",
                "BENTLEY",
                "SSANGYONG",
                "PEUGEOT",
                "TOYOTA",
                "RENAULT",
                "ACURA",
                "ADAMO",
                "AGRALE",
                "ALFA ROMEO",
                "AMERICAR",
                "ASTON MARTIN",
                "AUDI",
                "BEACH",
                "BIANCO",
                "BMW",
                "BORGWARD",
                "BRILLIANCE",
                "BUICK",
                "CBT",
                "NISSAN",
                "CHAMONIX",
                "CHEDA",
                "CHERY",
                "CORD",
                "COYOTE",
                "CROSS LANDER",
                "DAEWOO",
                "DAIHATSU",
                "VOLVO",
                "DE SOTO",
                "DETOMAZO",
                "DELOREAN",
                "DKW-VEMAG",
                "SUZUKI",
                "EAGLE",
                "EFFA",
                "ENGESA",
                "ENVEMO",
                "FARUS",
                "FERCAR",
                "FNM",
                "PONTIAC",
                "PORSCHE",
                "GEO",
                "GRANCAR",
                "GREAT WALL",
                "HAFEI",
                "HOFSTETTER",
                "HUDSON",
                "HUMMER",
                "INFINITI",
                "INTERNATIONAL",
                "JAGUAR",
                "JEEP",
                "JINBEI",
                "JPX",
                "KAISER",
                "KOENIGSEGG",
                "LAUTOMOBILE",
                "LAUTOCRAFT",
                "LADA",
                "LANCIA",
                "LAND ROVER",
                "LEXUS",
                "LIFAN",
                "LINCOLN",
                "LOBINI",
                "LOTUS",
                "MAHINDRA",
                "MASERATI",
                "MATRA",
                "MAYBACH",
                "MAZDA",
                "MENON",
                "MERCURY",
                "MITSUBISHI",
                "MG",
                "MINI",
                "MIURA",
                "MORRIS",
                "MP LAFER",
                "MPLM",
                "NEWTRACK",
                "NISSIN",
                "OLDSMOBILE",
                "PAG",
                "PAGANI",
                "PLYMOUTH",
                "PUMA",
                "RENO",
                "REVA-I",
                "ROLLS-ROYCE",
                "ROMI",
                "SEAT",
                "UTILITARIOS AGRICOLAS",
                "SHINERAY",
                "SAAB",
                "SHORT",
                "SIMCA",
                "SMART",
                "SPYKER",
                "STANDARD",
                "STUDEBAKER",
                "TAC",
                "TANGER",
                "TRIUMPH",
                "TROLLER",
                "UNIMOG",
                "WIESMANN",
                "CADILLAC",
                "AM GEN",
                "BUGGY",
                "WILLYS OVERLAND",
                "KASEA",
                "SATURN",
                "SWELL MINI",
                "SKODA",
                "KARMANN GHIA",
                "KART",
                "HANOMAG",
                "OUTROS",
                "HILLMAN",
                "HRG",
                "GAIOLA",
                "TATA",
                "DITALLY",
                "RELY",
                "MCLAREN",
                "GEELY",

        };
        ArrayAdapter<String> adapter = new ArrayAdapter<String>(this, android.R.layout.simple_spinner_item, ArrayMarca);
        adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
        Marca.setAdapter(adapter);

    }

    public void SalvarCarrosOpcoes(View view) {
        if (validarCamposCarrosOpcoes()==true) {

            carro = new Carro();
            String modeloCar = Modelo.getSelectedItem().toString();
            Toast.makeText(getApplicationContext(),""+modeloCar,Toast.LENGTH_SHORT).show();
            String marcaCar = Marca.getSelectedItem().toString();
            Toast.makeText(getApplicationContext(),""+marcaCar,Toast.LENGTH_SHORT).show();
            String anoFab = AnoFab.getSelectedItem().toString();
            Toast.makeText(getApplicationContext(),""+anoFab,Toast.LENGTH_SHORT).show();

            carro.setModelo(modeloCar);
            carro.setMarca(marcaCar);
            carro.setAnoFab(anoFab);

            carro.salvarCarros();

            finish();
        }
    }
    public void inicializa() {
        Marca = findViewById(R.id.sp_Marca);
        Modelo = findViewById(R.id.sp_modelo);
        AnoFab = findViewById(R.id.sp_anoFab);
    }


    private boolean validarCamposCarrosOpcoes() {
        if (marcaCar == "MARCA" || modeloCar == "MODELO") {
            Toast.makeText(getApplicationContext(),
                    "FALTA SELECIONAR UM /n DOS DADOS PFV VERIFICAR",Toast.LENGTH_SHORT).show();
            return false;
        }else {
            return true;
        }
    }

}